// components/Header/Header.tsx
import Logo from '../Logo/Logo';
import SearchBar from '../SearchBar/SearchBar';
interface HeaderProps {
    value?: string;
}
const Header: React.FunctionComponent<HeaderProps> = (props) => (
    <div className={`container-full`}>
        <div className={`side-bar`}>
            <Logo small />
        </div>
        <div className={`side-container`}>
            <SearchBar value={props.value} />
        </div>
    </div>
);

export default Header;

// src/app/components/commons/header/header.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html'
})
export class HeaderComponent {
  @Input() searchValue: string;
  public smallLogo = true;
}

<div class="container-full">
  <div class="side-bar">
    <app-logo routerLink="/" [small]="smallLogo"></app-logo>
  </div>
  <div class="side-container">
    <app-search-bar [searchValue]="searchValue"></app-search-bar>
  </div>
</div>
